update:
	go mod tidy
	go get -u ./...

test:
	go test ./...

lint:
	golangci-lint run -v --max-issues-per-linter 0 --max-same-issues 0 ./...

vet:
	go tool staticcheck ./...
	golangci-lint run -v --max-issues-per-linter 0 --max-same-issues 0 ./...

govulncheck:
	go tool govulncheck ./...